spring:
  cloud:
    consul:
      port: 8500
      discovery:
        healthCheckPath: /wanzi/health
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${random.value}
  application:
    name: name-service
server:
  port: 8502