# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    config.vm.box = "comiq/dockerbox"

    # Name Service
    config.vm.network "forwarded_port", guest: 8502, host: 8502
    # User Service
    config.vm.network "forwarded_port", guest: 8503, host: 8503
    # Consul interface
    config.vm.network "forwarded_port", guest: 8500, host: 8500

    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.provision "shell", path: "bootstrap.sh"
end
