spring:
  cloud:
    consul:
      host: 192.168.33.1
      port: 8500
      discovery:
        healthCheckPath: /wanzi/health
        healthCheckInterval: 15s
        instance-id: user-service
  application:
    name: user-service
server:
  port: 8503
feign:
  hystrix:
    enabled: true