spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /wanzi/health
        healthCheckInterval: 15s
        instance-id: user-service
  application:
    name: user-service
  zipkin:
      base-url: http://localhost:9411
server:
  port: 8503
feign:
  hystrix:
    enabled: true