spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /wanzi/health
        healthCheckInterval: 15s
        instance-id: consul-name
  application:
    name: consul-name
server:
  port: 8502